#!/usr/bin/perl
$WORLD = $ENV{'WORLD'};
$who = $ARGV[0];
$s = `pick $who/.i - '^AC' `;
$s = 10 if $s eq '';
chomp($s);
print STDERR "($s)";

$dex = `getab dex $who`;
chomp($dex);

#Modificadores
$s += `pick $WORLD/tables/dexterity HitProb '^$dex'`;
$modca = `cat $who/.modca 2>&- | cut -f2 `;
@modcalist = split("\n",$modca);
for (@modcalist)
{
$s += $_ ;
}
print $s;
