#!/usr/bin/perl
$WORLD = $ENV{'WORLD'};
$path = './';
$path = $ARGV[0] if ($#ARGV == 0);
$path = "$path/" if !($path =~ /\/$/);

foreach (split('\n',`ls $path`))
{
        
        $per{$_} = `cat $_/.attack`;
        if ($per{$_} =~ /init\t(\d+)/)
        {
	 push(@{ $init{$1}}, $_);
        }
}

foreach $i (sort {$a <=> $b} keys (%init) )
{
        print "Round $i\n";
        foreach $s ( @{$init{$i}})
        {
	 #print $per{$s};
	 #$per{$s} =~ /target\t(\w+)/;
	 $per{$s} =~ /target\t(\w+)/;
	 $tg = `target $1`;
	 
	 #$1 ataca a $tg
	 
	 $life = `hp $tg 0>&-`;
	 $th=`tohit $tg $s`;
	 $roll = `pick $s/.attack - roll`;
	 chomp($roll);
	 $roll = $roll + `pick $s/.ab - HitProb`;
	 $sizeoftg = `pick $s/.i - Size`;
	 chomp($sizeoftg);
	 $sizeoftg = 'M' if ($sizeoftg eq '');
	 
	 unless ($th eq '')
	 { 
	   chomp($life);
	   print "($i) $s attacking $tg ($sizeoftg, $life hp). Rolled $roll, $th \n";
	   if ($roll > $th)
	   {
	        $damage = `pick $s/.using - $sizeoftg | cast`;
		$damage = $damage + `pick $s/.ab - DamageAdjust`;
		chomp($damage);
	   	print "HIT with $damage de danio!\n";
		$hp = `echo '-$damage' | hp $tg`;
		if ($hp <= 0)
		{
		  print "Murio!\n";
		  `pick $tg/.i - XP | sumxp $s;`;
		}
	   }
	   
	 }else{
	   print "($i) $s attacking $tg. \n";

	 }
	 `rm $s/.attack`;
	 
        }
        print "txt:";
        $descr{$i} = <>;
}
