#!/usr/bin/perl
#create weapons 'Espada corta'
$WORLD = $ENV{'WORLD'};
if ($#ARGV==-1)
{
print `ls $WORLD/magic/`;
die("create listfile.");
}

$lista = $ARGV[0];
if ($#ARGV==0)
{
print `cat $WORLD/magic/$lista`;
die("create listfile object.");
}
$elemento = $ARGV[1];
chomp($elemento);
$t = $elemento;
$t =~ s/\s+//g;
$elementname = "$lista$t";
$elementname = $ARGV[2] if ($#ARGV == 2);
`echo '\#$lista$t' > $elementname`;
`cat $WORLD/magic/$lista | grep '$elemento' | cut -f2 | perl >> $elementname`;
`cat $WORLD/magic/$lista | grep '$elemento' | cut -f3 >> $elementname`;
