#!/usr/bin/perl
#create weapons 'Espada corta'
$WORLD = $ENV{'WORLD'};
if ($#ARGV==-1)
{
print `ls $WORLD/tables/`;
die("create listfile.");
}

$lista = $ARGV[0];
if ($#ARGV==0)
{
print `cat $WORLD/tables/$lista`;
die("create listfile object.");
}
$elemento = $ARGV[1];
$s =  `cat $WORLD/tables/$lista | grep -i -E '^Item\\s|^$elemento\\s' | rotatetable`;
#print STDERR $s;
$s =~ /^(.*?)\n/;
$t = $1;
$t =~ s/\s+//g;
die if ($t eq 'Item');
if ($#ARGV == 2)
{
$name = $ARGV[2];
}else{
$name = "$lista$t";
}
$name = "${name}1" if (not ($name=~ /\d$/)) and (-e $name);	
$name++ while (-e $name);

open F, ">$name";
print "$name";
print F $s;
close F;
