#!/usr/bin/perl
use Switch;
    @race = ("Dwarf","Elf","Gnome","Half-elf","Halfling","Human");
    @req = ([[8,18], [3,18], [6,18], [3,18], [7, 18], [3, 18]],
            [[3,17], [6,18], [3,18], [6,18], [7, 18], [3, 18]],
            [[11,18],[7,18], [8,18], [6,18], [10,18], [3, 18]],
            [[3,18], [8,18], [6,18], [4,18], [6, 18], [3, 18]],
            [[3,18], [3,18], [3,18], [3,18], [3, 17], [3, 18]],
            [[3,17], [8,18], [3,18], [3,18], [3, 18], [3, 18]]  );
    @classes = ("Fighter","Paladin","Ranger","Mage","Specialist","Cleric","Druid","Thief","Bard");

$WORLD = $ENV{'WORLD'};
print STDERR $str = `cast Strength 3d6`,"\n";
print STDERR $dex = `cast Dexterity 3d6`,"\n";
print STDERR $con = `cast Constitution 3d6`,"\n";
print STDERR $int = `cast Intelligence 3d6`,"\n";
print STDERR $wis = `cast Wisdom 3d6`,"\n";
print STDERR $cha = `cast Charisma 3d6`,"\n";

$choose=1;
while (1)
{
print STDERR "1.$race[0]/2.$race[1]/3.$race[2]/4.$race[3]/5.$race[4]/6.$race[5]:\n";
$r = <>-1;

if (0 <= $r and $r <= ($#race)) {}else{next;}

if (($str >= $req[0][$r][0]) and ($str <= $req[0][$r][1])) {
if (($dex >= $req[1][$r][0]) and ($dex <= $req[1][$r][1])) {
if (($con >= $req[2][$r][0]) and ($con <= $req[2][$r][1])) {
if (($int >= $req[3][$r][0]) and ($int <= $req[3][$r][1])) {
if (($wis >= $req[4][$r][0]) and ($wis <= $req[4][$r][1])) {
if (($cha >= $req[5][$r][0]) and ($cha <= $req[5][$r][1])) {

    last;
}}}}}}

}

$i=1;
$s='';
$s="$s" . $i++ . ".$_/" for (@classes);
chop($s);
$choose=1;
while (1)
{
print STDERR "$s:\n";
$c = <>-1;

if (0 <= $c and $c <= ($#classes)) {}else{next;}

if ($str >= `pick $WORLD/tables/classabilityminimums $classes[$c] str`)  {
if ($dex >= `pick $WORLD/tables/classabilityminimums $classes[$c] dex`)  {
if ($con >= `pick $WORLD/tables/classabilityminimums $classes[$c] con`)  {
if ($int >= `pick $WORLD/tables/classabilityminimums $classes[$c] int`)  {
if ($wis >= `pick $WORLD/tables/classabilityminimums $classes[$c] wis`)  {
if ($cha >= `pick $WORLD/tables/classabilityminimums $classes[$c] cha`)  {

    last;
}}}}}}

}
print STDERR "Nombre:\n"; $name = <>;
chomp($name);
print STDERR "Breve descripcion:\n"; $text = <>;
chomp($text);

print STDERR "Level:\n"; $level = <>;

switch ($r){
    case 1 #dwarf
    {
        $age = `cast Age 5d6+40`;
    }
}


#switch ($r) {
#case 0
#{

#}

print `mkdir $WORLD/characters/p$name`;
#%print `ln -s $WORLD/characters/p$name`;
open F, ">$WORLD/characters/p$name/.i";

print F "name\t$name\n";
print F "description\t$text\n";
print F "race\t$race[$r]\n";
print F "str\t$str\n";
print F "dex\t$dex\n";
print F "con\t$con\n";
print F "int\t$int\n";
print F "wis\t$wis\n";
print F "cha\t$cha\n";
print F "class\t$classes[$c]\n";
close F;
