#!/usr/bin/perl
#multiply archivo

$who = $ARGV[0];
$N = `pick $who - Number | cast`;
print STDERR $N;
for $i (1..$N)
{
 print STDERR $i;
`cat $who | grep -v '^Number' | mysed > $who$i`;
 print "$who$i\n";
}

`remove $who`;
