#!/usr/bin/perl
#instantiates files, things, creatures, etc...

if ($#ARGV >= 0)
{@nom = @ARGV;}
else
{push(@nom,$_) while(<>);}


for(@nom)
{
	print $_;
	chomp; chomp;
	$f = $_;
	$content = `cat $f | mysed`;
	open F, ">$f";
	print F $content;
	close F;
}

