#!/usr/bin/perl
#instantiates files, things, creatures, etc...

while(<>)
{
#print $_;
	s/Alignment\tAny/Alignment\tLG,LN,LE,NG,NN,NE,CG,CN,CE/;
	chomp;
	@f = split('\t');
	for (@f)
	{
		if (/,/)
		{
		  @opts = split(',');
		  $_ = $opts[int(rand($#opts+1))];
		}
		unless ($f[0] =~ /Attacks/)
		{
		  while (s/(\d+d[\+\-\*\/x\d]+)/`echo $1 | cast | tr -d '\n'`/eg){}
		}
		$out = "$out$_\t";
	}
	chop($out);
	$out = "$out\n"
}
chop($out);
print $out;
