#!/usr/bin/perl
$charname = 'murray';
$WORLD = $ENV{'WORLD'};
$file =  `cat $WORLD/public_html/historia.html`;
@logs = split('\s',`ls $WORLD/log/`);
$rows=$#logs+1;

  $datarow='';
  my $i=-1;
foreach $time (@logs)
{
#$i++;
$s=0;
  #$oldtime=$time;
print `printtime $time \n`;
$alllines=`cat $WORLD/log/$time`;
@lines=split('\n',$alllines);
foreach $l (@lines)
{
$ap = "'";
$l =~ s/\'//g;
$l =~ s/\`//g;
$l =~ s/\"//g;

  print "$l\n";
  
  @col = split('\t',$l);
  $who = $col[0];
  $txt = $col[1];
#  $txt=~ /([^\.]*)\./;
#  $tit = $1;
  $hs=$time;
  $h = ($hs % 24);
  $min = int(($h-int($h))*60);
  $d = int($hs/24);
  $y = int($d/364);
  $d = $d % 364;
  #$val = $i;
  for (split(',',$who))
  {
  /(\w+)\((\d+)\)/;
  #print $who, $1, $2;
  $val = $2;
  $i=0+$nrows{$1};
  $datarow{$1} =$datarow{$1} . "data.setValue($i, 0, new Date($y, 0, $d, $h, $min, $s));data.setValue($i, 1, $val);data.setValue($i, 2, ' ');data.setValue($i, 3, '$txt');\n";
#$1 $tit
  $nrows{$1} = $nrows{$1}+1;
  }
  $s++;
  }
}

for (keys %datarow)
{
$myfile = $file;
$myfile =~ s/insertdata/$datarow{$_}/;
$myfile =~ s/insertCharacterName/$_/;
$myfile =~ s/insertNumberOfRaws/$nrows{$_}/;
open FILE, ">", "$WORLD/public_html/hist$_.html" or die $!;
print FILE $myfile;
close FILE;
}
