#!/usr/bin/perl
while ($l = <>)
{
while ($l =~ s/(\d+)\%\((.*?)\)/replacing/)
{
 $qno = '';
 @opts = split(';',$2);
 $qsi = $opts[0];
 $qno = $opts[1] if ($#opts > 0);
 if (rand(100)>$1)
 {
 $l =~ s/replacing/$qno/; 
 }else{
 $l =~ s/replacing/$qsi/; 
 }
}
print $l;
}
