#!/usr/bin/perl
$WORLD = $ENV{'WORLD'};
$who = $ARGV[0]; #name of the guy
chop($who) if (substr($who,-1,1) eq '/');
unless (-e "$who"){$who =~  s/([A-Z]\w*)$/p$1/ if not ($who =~ /p[A-Z]\w*$/);}
$who = "$WORLD/characters/$who" if not (-e "$who");
unless (-e "$who")
{
$path = './';

foreach (split('\n',`ls $path`)){
$who = $_ if /$ARGV[0]/i;
}

}
$name=$who;
print $name;
