#!/usr/bin/perl
#thac0
$WORLD = $ENV{'WORLD'};
$who = $ARGV[0];
$s = `cat $who/.i $who/.lastlvl | grep -i THAC0 | cut -f2`;
chomp($s);
print STDERR "($s)";

$str = `getab str $who`;
chomp($str);

$s -= `pick $WORLD/tables/strength HitProb '^$str'`;
print $s;
