#!/usr/bin/perl
$path = $ARGV[0];
@readcl = split("\t",`cat $path.map`);
@cl = map( $_?"\033[34m$path${_}\033[0m":"\033[0m" ,@readcl);
@cl = map( $_?"$path${_}":"" ,@readcl);
@ccl = map((-e $_)?"\033[34m$_\033[0m":"$_" , @cl);
@ccl = map((-e $_)?"\033[34m$_\033[0m":"\033[0m$_\033[0m" , @cl);

#print "\033[34m";
printf("%*s\n",50+length($cl[12])/2,$ccl[12]); 
printf("%20s%20s%20s%-20s\n",'',$ccl[11],'',$ccl[1]);
printf("%10s%20s%40s%-20s\n",'',$ccl[10],'',$ccl[2]);
printf("%20s%*s%*s%-20s\n",$ccl[9],30+length($cl[0])/2,$ccl[0],30-length($cl[0])/2,'',$ccl[3]);
printf("%10s%20s%40s%-20s\n",'',$ccl[8],'',$ccl[4]);
printf("%20s%20s%20s%-20s\n",'',$ccl[7],'',$ccl[5]);
printf("%*s\n",50+length($cl[6])/2,$ccl[6]); 
#print "\033[0m";
