#!/usr/bin/perl
$path = $ARGV[0];
@readcl = split("\t",`cat $path.map`);
@cl = map( $_?"\033[34m$path${_}\033[0m":"\033[0m" ,@readcl);
@cl = map( $_?"$path${_}":"" ,@readcl);
print "\033[34m";
printf("%*s\n",50+length($cl[12])/2,$cl[12]); 
printf("%20s%20s%20s%-20s\n",'',$cl[11],'',$cl[1]);
printf("%10s%20s%40s%-20s\n",'',$cl[10],'',$cl[2]);
printf("%20s%*s%*s%-20s\n",$cl[9],30+length($cl[0])/2,$cl[0],30-length($cl[0])/2,'',$cl[3]);
printf("%10s%20s%40s%-20s\n",'',$cl[8],'',$cl[4]);
printf("%20s%20s%20s%-20s\n",'',$cl[7],'',$cl[5]);
printf("%*s\n",50+length($cl[6])/2,$cl[6]); 
print "\033[0m";
