#!/usr/bin/perl
$|++;

print "Objetivo de tu ataque:\n";
$t = <stdin>;
chomp($t);
$i = `cast 'Atacas a $t. Ahora tu iniciativa' 1d10`;
print "Tu iniciativa es $i.\n";
$hd = `cast 'Finalmente tu hit dice' 1d20`;
print "Hit dice: $hd\n";
