#!/usr/bin/python


import smtplib
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase
from email.MIMEText import MIMEText
from email import Encoders
import os
import sys

gmail_user = "dungeon.bot.master@gmail.com"
gmail_pwd = "pablodupuy2"

def mail(to, subject, text, attach):
   msg = MIMEMultipart('related')

   msg['From'] = gmail_user
   msg['To'] = to
   msg['Subject'] = subject
   msg.preamble = 'This is a multi-part message in MIME format.'

   #msg.attach(MIMEText(text))
   msg.attach(MIMEText(text))

   part = MIMEBase('application', 'octet-stream')
   part.set_payload(open(attach, 'rb').read())
   Encoders.encode_base64(part)
   part.add_header('Content-ID',
           'attachment; filename="%s"' % os.path.basename(attach))
   msg.attach(part)

   mailServer = smtplib.SMTP("smtp.gmail.com", 587)
   mailServer.ehlo()
   mailServer.starttls()
   mailServer.ehlo()
   mailServer.login(gmail_user, gmail_pwd)
   mailServer.sendmail(gmail_user, to, msg.as_string())
   # Should be mailServer.quit(), but that crashes...
   mailServer.close()

#f=open('/home/bot/world/events/intro','r')
#f=open('/home/bot/world/commands/emailtest','r')

#str=f.readlines()
str = sys.stdin.readlines()
print str
mail(sys.argv[1],
   sys.argv[2],
   "".join(str),sys.argv[3])
